api:
  url: https://CHANGEME.contrastsecurity.com/Contrast
  api_key: CHANGEME
  service_key: CHANGEME
  user_name: CHANGEME@CHANGEME
application:
  name: broadleaf-xss
server:
  name: broadleaf-xss
protect:
  enabled: false
assess:
  enabled: true
agent:
  logger:
    level: DEBUG
